version: 2.1
orbs:
  barkendeploy: navikt/barkendeploy@dev:master
jobs:
  publish:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - barkendeploy/gradle-cache-restore
      - run:
          name: Build artifact
          command: ./gradlew build -x test -x signJar
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Sign jar
          command: |
            export GPG_KEY_ARMORED=$(echo $GPG_KEY_BASE64 | base64 --decode)
            ./gradlew signJar --stacktrace
      - run:
          name: Publish artifacts
          command: ./gradlew publish
      - barkendeploy/gradle-cache-persist
  build:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - barkendeploy/gradle-cache-restore
      - run:
          name: Run tests
          command: ./gradlew test

workflows:
  version: 2
  build_and_publish:
    jobs:
      - publish:
          context: Maven Central Release
          filters:
            branches:
              only: master
