name: Deploy to dev
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build-push-deploy:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build artifact
        run: |
          ./gradlew build -x test
      - name: Run tests
        run: |
          ./gradlew test