name: Publish artifacts
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  snyk-test:
    name: Checkout code and analyze dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk16@master
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --org=teamsykmelding --all-sub-projects --severity-threshold=high
  build_and_release:
    runs-on: ubuntu-latest
    needs: [snyk-test]
    steps:
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Checkout code
        uses: actions/checkout@master
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup gradle dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: test and build
        run: ./gradlew -Pversion="1.$(echo $GITHUB_SHA | cut -c1-7)-SNAPSHOT" build
      - name: upload artifact
        run: ./gradlew -Pversion="1.$(echo $GITHUB_SHA | cut -c1-7)-SNAPSHOT" publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
